### PR TITLE
Added option to install Beta

### PR DESCRIPTION
**Pull request by ovpc**
If BETA=yes it adds "pre"  to the download path. ${PREFIX}
Haven't tested this yet, will do so shortly after creating pull request

### CODE REVIEW

**Comment by ovpc** [comment]
the ${PREFIX} some doesnt work, although 

`pi@nextcloudpi:~ $ echo wget -q https://download.nextcloud.com/server/${PREFIX}releases/nextcloud-$VER_.tar.bz2
wget -q https://download.nextcloud.com/server/releases/nextcloud-.tar.bz2`

When manually adding pre to download PATH /prereleases/ the install works!

**Comment by testbird** [comment]
> If BETA=yes it adds "pre"

I see only [[ "BETA_" == yes ]] in the diff (why are there so many ending "_"s used in this script?).  However, here, that is just a string  and I don't see how this test would ever be true. The script would need to inherit and evaluate something like a ${BETAINSTALL} variable from somewhere.

**Comment by nachoparker** [comment]
if a variable ends in "_" then it will be changeable from ncp-web and nextcloudpi-config.

See the [dev docs](https://github.com/nextcloud/nextcloudpi/wiki/Developer-guide)

**Comment by nachoparker** [comment]
applied, thanks... I'll tweak the typo and test it

**Pull request merged**
