### PR TITLE
(add function)Fix some errors that nextcloud will alert after the update.

### PR DESCRIPTION
**Pull request by chiyi4488**
Fix some errors that nextcloud will alert after the update.

*****This is just one of my ideas and has not been tested. *****
After updating to NC14, the system will display security and other issues in the overview. If can fix the problem before the display, the user will be much more convenient.

Please ask the main developers to test, thank you.

### CODE REVIEW

**Comment by nachoparker** [comment]
Awesome, thanks chiyi. I think we can put this better at the end of `bin/nc-update-nc`.

**Comment by chiyi4488** [comment]
Put on "clean up"??

**Comment by chiyi4488** [comment]
Or "done"??

**Comment by nachoparker** [comment]
I would say... [here](https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp-update-nc#L174)

**Comment by chiyi4488** [comment]
I change it. look like ok?

**Comment by nachoparker** [comment]
great, thank you chiyi!

**Pull request closed without merging**
