### PR TITLE
Fix bug in nc-previews-auto.sh

### PR DESCRIPTION
**Pull request by m-breitbach**
Fix typo that prevents the feature from being disabled.

### CODE REVIEW

**Comment by theCalcaholic** [comment]
Thanks again for the PR. I'll check it and consider it for v1.53.3

**Review by theCalcaholic — CHANGES_REQUESTED** [review]
Hi, this generally looks good, but since the apps name is `nc-previews-auto` not `ncp-previews-auto` I think it would good if the cron file follows this naming scheme. Could you adjust this? Then I'm happy to merge it.

**Comment by theCalcaholic** [comment]
Looks good, thank you!

**Review by theCalcaholic — APPROVED** [review]

**Comment by m-breitbach** [comment]
Somehow, the commit didn't make it into the release.

**Pull request merged**
