### PR TITLE
Skip $DATADIR when fixing permissions

### PR DESCRIPTION
**Pull request by MB-Finski**
The data directory contains potentially hundreds of thousands files and iterating through all of them thrice will make the upgrade process slow (hours instead of minutes). This arguably results in unnecessary downtime.

This commit proposes skipping fixing permissions/ownership for the data directory since "mv" (should) perserve them when performing a simple upgrade. This would make upgrading considerably faster.

Signed-off-by: MB-Finski <64466176+MB-Finski@users.noreply.github.com>

### CODE REVIEW

**Comment by MB-Finski** [comment]
I left this as draft, still, since I'm not 100% sure if there are good reasons why the permissions/ownership should be resetted at each upgrade.

**Comment by theCalcaholic** [comment]
The fix-permissions app is specifically meant to fix permissions for the data directory (e.g. after manually copying files or after restoring a backup) :)

**Comment by theCalcaholic** [comment]
This will soon be relevant, because the data directory will not remain inside /var/www/nextcloud anymore (WIP in https://github.com/nextcloud/nextcloudpi/tree/fix/nc-restore-keep-nc-data)

**Comment by theCalcaholic** [comment]
`ncp-update-nc` was largely rewritten for the upcoming version 24.0.5. Not fixing permissions for the data directory was part of that rewrite :)

**Pull request closed without merging**
