### PR TITLE
add hover text for ncp admin header icons

### PR DESCRIPTION
**Pull request by pusherman**
resolves issue #514

### CODE REVIEW

**Comment by nachoparker** [comment]
great, thank you. I will merge it in a couple weeks and include in the next release!

we need a lot of help with ncp-web

**Comment by pusherman** [comment]
Yeah, I plan on helping out with ncp-web as much as I can.  Let me know if there are any specific ones that would be really helpful to try to take care of.  Otherwise I will just start picking off the issues as I come across them.

**Comment by nachoparker** [comment]
that's great, very much appreciated!

well you can probably already see many deficiencies, so feel free to suggest changes. 

I put together a little list https://github.com/nextcloud/nextcloudpi/issues/622 but feel free to suggest stuff, I am sure you are better at webdev than me :D

**Comment by nachoparker** [comment]
works great. Implemented in `v0.59.10`

Thanks!

**Pull request closed without merging**
