### PR TITLE
fix #595

### LINKED ISSUE #595: proposed fail2ban enhancement using UFW logs
Hello.
Seeing some connection attempts against server.
Has therefore modified fail2ban (added).

/etc/fail2ban/jail.local

[nextcloud2]
enabled = true
port = http,https
filter = nextcloud2
logpath = /data/nextcloud/nextcloud.log
maxretry = 1
findtime = 1
bantime = 604800 ; 1 week

[ufwban]
enabled = true
port = ssh, http, https
filter = ufwban
logpath = /var/log/ufw.log
maxretry = 1
findtime = 1
bantime = 604800
action = ufw

and

/etc/fail2ban/filter.d/nextcloud2.conf

[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*"remoteAddr":"".Trusted domain error.$
ignoreregex =

and

/etc/fail2ban/filter.d/ufwban.conf

[INCLUDES]
before = common.conf

[Definition]
failregex = UFW BLOCK.* SRC=
ignoreregex =

### PR DESCRIPTION
**Pull request by dmaroulidis**
Add a ufw jail and filter.

### CODE REVIEW

**Comment by nachoparker** [comment]
thank you! I will test it and add it to the next release

**Comment by dmaroulidis** [comment]
@nachoparker It was great contributing to the project!

**Comment by nachoparker** [comment]
our project ;)

**Comment by dmaroulidis** [comment]
> our project ;)

Yeah!

**Comment by nachoparker** [comment]
Applied, thank you! 

https://github.com/nextcloud/nextcloudpi/commit/29dc69f2d7dbcef1ecde0f42f30579db13b33a27

**Comment by nachoparker** [comment]
I tested this, an there is a problem: if `/var/log/ufw.log` doesn't exist then fail2ban won't start

```
ERROR  No file(s) found for glob /var/log/ufw.log
ERROR  Failed during configuration: Have not found any log file for ufwban jail
```

maybe there's a way to fix that by fail2ban configuration

**Comment by nachoparker** [comment]
Thanks! I applied your changes to `devel` because there was a conflict

**Pull request closed without merging**
