### PR TITLE
Update ncp-check-version

### PR DESCRIPTION
**Pull request by testbird**
specific error (allows admin to fix)

### CODE REVIEW

**Comment by nachoparker** [comment]
thanks, will apply soon

**Comment by nachoparker** [comment]
applied

please, in the future only send PRs to the _devel_ branch

**Comment by testbird** [comment]
Your error handling changes that I modified did not show up in the devel branch.

**Comment by nachoparker** [comment]
I see, maybe it wasn't updated?

anyway, it's fine, just letting you know ;)

**Pull request closed without merging**
