### PR TITLE
nc-autoupdate-ncp: Append to log instead of replace

### PR DESCRIPTION
**Pull request by llucax**
The log is being replaced on each run instead of appended to.

### CODE REVIEW

**Comment by nachoparker** [comment]
applied, thanks!

**Comment by llucax** [comment]
Any particular reason why PR aren't being just merged with GitHub?

**Comment by llucax** [comment]
Asking because I can't even see the changes in master (at least yet).

**Comment by nachoparker** [comment]
it's in my local branch. The reason is that I have a script to tag it and add the info from every commit to the changelog

https://github.com/nextcloud/nextcloudpi/blob/master/changelog.md

**Pull request closed without merging**
