### PR TITLE
Reverse proxy and hsts improvements

### PR DESCRIPTION
**Pull request by AvverbioPronome**
This should solve issue #777 and use more sensible defaults for the hsts header (that is ignored anyway when not served over https)

### CODE REVIEW

**Comment by nachoparker** [comment]
Also, we should apply these changes for existing users through the `nc-update` mechanism. See the `updates/` folder.

**Comment by AvverbioPronome** [comment]
> Note that by removing HSTS from the global settings you are also removing it from ncp-web

I didn't think about this but it's probably not an issue, hsts is (sub)domain-wide. Where's the ncp-web virtualhost defined?

> Also, we should apply these changes for existing users through the `nc-update` mechanism. See the `updates/` folder.

Replace or edit? I can't imagine a safe way of doing that.

**Comment by AvverbioPronome** [comment]
I've been looking at the source code to understand where/when to apply hsts headers to ncp-web, and I realised that we can't apply them at the very beginning with a self signed certificate, we need to wait for a Let's Encrypt certificate to be obtained and working. 

Ideas?

(I also thought we can probably create an `/etc/apache2/snippets/ directory for all the reused configurations across the virtualhosts, but I wanted to hear from you before messing with it.)

(Another idea more could be to move from certbot to acme.sh or bacme -- which are shell scripts instead of full-fledged python applications)

**Comment by nachoparker** [comment]
> (Another idea more could be to move from certbot to acme.sh or bacme -- which are shell scripts instead of full-fledged python applications)

We have been toying with this idea, since you can use non standard ports, but certbot is a defacto standard and it works well, so we didn't see a reason to go through the hassle.

**Comment by nachoparker** [comment]
> (I also thought we can probably create an /etc/apache2/snippets/ directory for all the reused configurations across the virtualhosts, but I wanted to hear from you before messing with it.)

I would be fine with that.

> I've been looking at the source code to understand where/when to apply hsts headers to ncp-web, and I realised that we can't apply them at the very beginning with a self signed certificate, we need to wait for a Let's Encrypt certificate to be obtained and working.

I think that if we just leave them where they were they apply to every SSL connection, no matter if there are cert changes.

**Comment by nachoparker** [comment]
ncp-web vhost -> https://github.com/nextcloud/nextcloudpi/blob/master/ncp.sh

**Comment by AvverbioPronome** [comment]
> I think that if we just leave them where they were they apply to every SSL connection, no matter if there are cert changes.

Yes and no:
- right now the header gets sent on http too, even if it's meaningless -- but this also means that if I use a reverse proxy I send **two** hsts headers: my own from the tls terminator, and ncp's one.
- a possible issue: hsts *and* a self-signed certificate pretty much means disallowing any connection. :D

**Comment by AvverbioPronome** [comment]
> We have been toying with this idea, since you can use non standard ports, but certbot is a defacto standard and it works well, so we didn't see a reason to go through the hassle.

Certbot can use different ports as well, it's not about features (ok, it is if we want to use elliptic curve certificates), it's more about reducing dependencies.

**Comment by AvverbioPronome** [comment]
I think as far as improvements/new features are concerned, this pull request is done.

I/we should get it ready to be merged. You say the `nc-update` mechanism?

**Comment by nachoparker** [comment]
applied, many thanks!

**Pull request closed without merging**
