### PR TITLE
Change email program from PHP to Sendmail

### PR DESCRIPTION
**Pull request by TomTurnschuh**
PHP seems to be no longer supported in Nextcloud 14.
This modification might need further testing in different environments.

### CODE REVIEW

**Comment by nachoparker** [comment]
Hi, thanks!

have you tested this change? you can send a test email if you have your email details configured in the user section.

**Comment by TomTurnschuh** [comment]
I tested it on my ODROID and Raspberry Pi devices, but I cannot conduct tests in different environments.
I only changed the config file on my instances, and did not test with the altered nc-init file. However, the new value corresponds to the config entry when setting this directly in Nextcloud.

**Comment by nachoparker** [comment]
So you sent and received the test email... great.

Yeah if you made the change through that command and that works don't need to test the nc-init part.

Thanks again!

**Comment by nachoparker** [comment]
Thank you, applied.

I modified your commit to include the modification in `update.sh` so that users that upgrade get the change.

Thanks!

**Pull request closed without merging**
