### PR TITLE
Creat new chinese translate and update chinese translate.

### PR DESCRIPTION
**Pull request by chiyi4488**

### CODE REVIEW

**Comment by chiyi4488** [comment]
Hello??

**Comment by chiyi4488** [comment]
hello?

**Comment by nachoparker** [comment]
hi chiyi,

Sorry this is taking so long to merge but I am pretty busy. I am making big changes these days, I'll include these translations and other pending PRs soon

**Comment by nachoparker** [comment]
applied, thank you as always!!

**Comment by chiyi4488** [comment]
happy new year!!!!!:D

**Comment by nachoparker** [comment]
happy new year

**Pull request merged**
