### PR TITLE
fix: corrected diskspace calculation in case of docker usage

### PR DESCRIPTION
**Pull request by paschaef**
As mentioned in  #844 during backup in the ncp-update process there is the possiblity that no diskspace is available for the backup. Also it was mentioned that the backup is dataless and does not require a lot of space. 
However, running in a docker configuration the data-directory is a subdirectory of the `basedir` and hence size of `datadir`gets counted too eventhough `includedata` is disabled. 
This pull request aimed to correct the calculation for the free/occupied diskspace in docker configuration. If not in docker configuration calculation is done as before.

### CODE REVIEW

**Comment by nachoparker** [comment]
good catch

**Comment by nachoparker** [comment]
related to conversation here https://github.com/nextcloud/nextcloudpi/issues/858#issuecomment-478335791

**Comment by nachoparker** [comment]
This should not be tied to `/.docker-image`. If we are not using `INCLUDEDATA`, then we should exclude the size of the datadir from the calculation.

Also we should add some more space for the database dump, as per the conversation above.

Thanks!

**Comment by paschaef** [comment]
So for clarification of the directory structre (because I am only using the dockerized version). The directory structure looks as follows for **both** (docker, non-docker) cases:
```
/var/www/nextcloud/
/var/www/nextcloud/$(datadir)
```
Am I right?

Then the proposal is to remove the outer most `if` condition with `/.docker-image` and to do only this part: 
```bash
  if [[ "$includedata" == "yes" ]]
  then
    size=$((nsize + 100*1024))
  else #datadir is inside $basedir/nextcloud therefor substract
    size=$((nsize - dsize + 100*1024))
  fi
```

Any suggestions on how to estiamte the size of the database dump? Or would you like to make a (larger) hardcoded estimate as it is now?

**Comment by nachoparker** [comment]
hi

Yes, the dirs are `"$BASEDIR/nextcloud` and `"$BASEDIR"/nextcloud/data` in the docker or regular case.

Your proposed solution looks good to me. 

About the db dump... it's hard to tell. My dbdir is 1GiB and my dbdump is 300MiB, so I think that the easiest is to go from 100 to 500MiB extra

**Comment by paschaef** [comment]
Here we are.

**Comment by nachoparker** [comment]
Looks good! We only need to tweak the calculations like in this commit https://github.com/nextcloud/nextcloudpi/commit/c18273a0f69669dc8846e786ded7501cd46aeb96, which was fixed after you started working on this.

**Comment by paschaef** [comment]
This is done! Hope it is correct in this version now.

**Comment by nachoparker** [comment]
looks perfect now :)

**Comment by paschaef** [comment]
great :)

**Comment by nachoparker** [comment]
thanks!

**Comment by hunhejj** [comment]
I still have the above issue.

Nextcloudpi version: `1.31.0.`, running in docker.

Trying to upgrade nextcloud from `18.0.7.1` to `19.0.4`.

Fails with the same error as mentioned in #858: `free space check failed.  Need 873366317 Bytes`. Checked and there is way more space than that.

**Pull request merged**
