### PR TITLE
Update echo at end when init done.

### PR DESCRIPTION
**Pull request by ovpc**
More relevant info to what steps one should take.
Should I add same to end of nc-init? Would be nice to have variable that grabs and fills in the your_IP?

### CODE REVIEW

**Comment by nachoparker** [comment]
Nice! on many routers you can also try `nextcloudpi.lan` or `nextcloudpi` and that would work on windows and mac as well, if your router supports it.

You can add more commits to your branch and they will all be merged together, if you want to add that info.

This is the code I use normally to get the IP address, if you want to try that out

```
  IFACE="$( ip r | grep "default via" | awk '{ print $5 }' | head -1 )"
  IP="$( ip a show dev "$IFACE" | grep global | grep -oP '\d{1,3}(.\d{1,3}){3}' | head -1 )"  
 echo "your IP is $IP"
```

**Comment by nachoparker** [comment]
Looks good, tell me when it's tested ;)

**Comment by ovpc** [comment]
Tested in VM Debian9 basic-tools install
All good ! End of output below:
---------------------------------------

> NextCloudPi updated to version v0.67.6
> Activating nc-init
> Setting up a clean Nextcloud instance... wait until message 'NC init done'
> Setting up database...
> Setting up Nextcloud...
> Nextcloud was successfully installed
> Set mode for background jobs to 'cron'
> System config value tempdirectory => /var/www/nextcloud/data/tmp set to empty string
> System config value mysql.utf8mb4 set to boolean true
> System config value trusted_domains => 1 set to string 192.168.2.11
> System config value trusted_domains => 5 set to string nextcloudpi.local
> System config value trusted_domains => 7 set to string nextcloudpi
> System config value trusted_domains => 8 set to string nextcloudpi.lan
> System config value mail_smtpmode set to string sendmail
> System config value mail_smtpauthtype set to string LOGIN
> System config value mail_from_address set to string admin
> System config value mail_domain set to string ownyourbits.com
> calendar installed
> calendar enabled
> contacts installed
> contacts enabled
> notes installed
> notes enabled
> tasks installed
> tasks enabled
> news installed
> news enabled
> admin_notifications installed
> admin_notifications enabled
> previewgenerator installed
> previewgenerator enabled
> calendar enabled
> contacts enabled
> notes enabled
> tasks enabled
> news enabled
> admin_notifications enabled
> previewgenerator enabled
> System config value overwriteprotocol set to string https
> NC init done
> ~
> Done.
> First: Visit https://192.168.2.11/  https://nextcloudpi.local/ (also https://nextcloudpi.lan/ or https://nextcloudpi/ on windows and mac)
> to activate your instance of NC, and save the auto generated passwords. You may review or reset them
> anytime by using nc-admin and nc-passwd.
> Second: Type 'sudo ncp-config' to further configure NCP, or access ncp-web on https://192.168.2.11:4443/
> Note: You will have to add an exception, to bypass your browser warning when you
> first load the activation and :4443 pages. You can run letsencrypt to get rid of
> the warning if you have a (sub)domain available.
>

**Comment by ovpc** [comment]
You can merge this one, whenever you have time. ;-)

Was looking at terminal output when using a fresh image (so not curl installer) and all you get after first login as pi is a mention of ncp needing update, and to run ncp-config or ncp-update.
Which script is giving that info? 
I would like to do same as for install.sh and add more info there too....

**Comment by nachoparker** [comment]
awesome, thanks!

**Pull request merged**
